# Generated by Django 3.2.7 on 2021-09-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.IntegerField()),
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'idiomas',
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valorTexto', models.CharField(max_length=200)),
                ('valorNumero', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaModificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'parametros',
            },
        ),
        migrations.CreateModel(
            name='Lenguajes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modulo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaModificacion', models.DateTimeField()),
                ('idioma', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.idiomas')),
            ],
            options={
                'db_table': 'lenguajes',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaModificacion', models.DateTimeField()),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.estados')),
            ],
            options={
                'db_table': 'entidades',
            },
        ),
    ]
