# Generated by Django 3.2.7 on 2021-09-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
