# Generated by Django 3.2.7 on 2021-09-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210918_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lenguajes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
